# ─────────────────────────────────────────────────────────────────────────────#
# config.yaml
# date: 2024/11/05
# owner: Hongsu Jung
# ─────────────────────────────────────────────────────────────────────────────
role: server              # server | client
listen_host: 0.0.0.0      # 서버만 사용
listen_port: 5051
server_host: 192.168.0.10 # 클라만 사용
server_port: 5051
token: "CHANGE_ME_LONG_RANDOM"
heartbeat_sec: 10
client:
  client_id: "cam-node-01"   # 없으면 자동 생성
  capabilities: ["ffmpeg","yolo"]
  tags: ["lineA","gpu0"]
